- Vorhersage für Benzinpreise je Tankstelle
  - 1 Monat Vorausschau
  - gegebene Uhrzeit
  - Clustering
    - Autobahn?
    - Berufsverkehr?
    - Pampa?
- Tankstrategie
  - Fixed-Path-Gas-Station-Problem
  - leerer Tank an gegebener Tkst
  - pro Tkst auf Route:
    - berechne getankte Menge pro Tkst --> minimiere Kosten
- Deadline Impl: Ende Nov
- 2 Services: Vorhersage, Routing

* TODOS
** TODO Paper lesen
** TODO Data Exploration
** TODO KNN, KMeans: testen, ob gleiche kategorien gefunden werden, die wir finden (Autobahn etc)
* Database
- install postgresql
[[https://wiki.archlinux.org/index.php/PostgreSQL]]
#+begin_src sh
pacman -Syu postgresql
systemctl start postgresql
sudo -u postgres -i
initdb --locale $LANG -E UTF8 -D '/var/lib/postgres/data'
#+end_src
- create db
#+begin_src sh
sudo -u postgres -i
createdb infocup
#+end_src
- connect to db and create tables
#+begin_src sh
pgcli -d infocup
#+end_src
#+begin_src sql
create table stations (
  id integer primary key,
  station_name varchar(255),
  brand varchar(255),
  street varchar(255),
  house_number varchar(255),
  zip_code varchar(5),
  city varchar(255),
  lat float,
  lon float);
create table prices (
  id serial primary key,
  time_stamp timestamp,
  price integer,
  station_id integer references stations);
#+end_src
- import data
#+begin_src sh
python database.py
#+end_src
** Autobahn
- download germany-latest.osm.pbf von [[http://download.geofabrik.de/europe/germany.html]] hier verwendet: Stand 18.10.2017 14:14
- mv =germany-latest.osm.pbf= nach =WeitereDaten=
- install osmfilter, osmconvert und osmosis
#+begin_src sh
pacaur -S osmfilter osmconvert osmosis
#+end_src
- convert pbf nach o5m für schnellere bearbeitung
#+begin_src sh
osmconvert germany-latest.osm.pbf -o=germany.o5m
#+end_src
- filter autobahn
#+begin_src sh
osmfilter germany.o5m --keep= --keep-relations="network=BAB" > autobahn.osm
#+end_src
- install postgis extension, create schema
#+begin_src sh
pacman -Syu postgis
pgcli -d infocup
#+end_src
#+begin_src sql
create extension postgis;
create extension hstore;
#+end_src
#+begin_src sh
psql -d infocup -f /usr/share/osmosis/script/pgsnapshot_schema_0.6.sql
psql -d infocup -f /usr/share/osmosis/script/pgsnapshot_schema_0.6_linestring.sql 
#+end_src
- read o5m, write postgis
#+begin_src sh
osmosis --truncate-pgsql database=infocup
osmosis --read-xml autobahn.osm --log-progress --write-pgsql database=infocup
#+end_src
- add ref col to ways for better grouping
#+begin_src sql
alter table ways add ref varchar(255);
update ways set ref = tags -> 'ref';
#+end_src

*** Notes
- The data in Open Street Map database is stored in a gcs with units decimal degrees & datum of wgs84. (EPSG: 4326)
- The Open Street Map tiles and the WMS webservice, are in the projected coordinate system that is based on the wgs84 datum. (EPSG 3857)
- table relations enthält die relationen wie zb A 81
  - table relations_members mapt ways und nodes auf relations (bei Autobahnen nur ways)
  - ways haben eine linestring column mit der die geometrie angezeigt werden kann [[http://arthur-e.github.io/Wicket/sandbox-gmaps3.html]]
** Vacations
- create table
#+begin_src sql
create table vacations (
  id serial primary key,
  state varchar(30) not null,
  type varchar(20) not null,
  start_date date not null,
  end_date date not null);
#+end_src
- import data
#+begin_src sh
python database.py vacations
#+end_src

* Papers
** ECONOMETRIC MODELS FOR OIL PRICE FORECASTING: A CRITICAL SURVEY
[[https://drive.google.com/open?id=0B0zREaCR-EN4c3BTSnVYU3pHWFk]]

In the last two years the price of oil and its fluctua-
tions have reached levels never recorded in the his-
tory of international oil markets. In 2007, the West
Texas Intermediate (WTI) oil price, one of the most
important  benchmarks  for  crude  oil  prices,  aver-
aged around 72 $/b, while in 2008 the WTI price was
around  100  $/b, with  an  increase  of  nearly  38  per-
cent  over  the  previous  year.  Within  the  past  six
months, WTI  daily  spot  prices  ranged  from  almost
150 $/b in early July to about 30 $/b towards the end
of 2008.
The  determinants  of  past, current, and  future  levels
of the price of oil and its fluctuations have been the
subject of analysis by academics and energy experts,
given  the  relevance  of  crude  oil  in  the  worldwide
economy. Although the share of liquid fuels in mar-
keted  world  energy  consumption  is  expected  to
decline  from  37  percent  in  2005  to  33  percent  in
2030, and projected high oil prices will induce many
consumers to switch from liquid fuels when feasible,
oil will remain the most important source of energy,
and  liquid  fuel  consumption  is  expected  to  increase
at an average annual rate of 1.2 percent from 2005 to
2030 (EIA 2008).
The crucial question of whether oil prices will rise in
the  future  or  will  decline  again  is  timely. According
to EIA (2009), for example, under current economic
and world crude oil supply assumptions, WTI prices
are expected to average 43 $/b in 2009 and 55 $/b in
2010. The possibility of a milder recession or a faster
economic  recovery, lower  non-OPEC  production  in
response to current low oil prices and financial mar-
ket constraints, and more aggressive action to lower
production  by  OPEC  countries  could  result  in  a
faster  and  stronger  recovery  in  oil  prices.  Conse-
quently, it  is  extremely  important  for  economists  to
provide accurate answers to the complex problem of
forecasting oil prices.
This  study  aims  at  investigating  the  existing  econo-
metric literature on forecasting oil prices. In particu-
lar, we (i) develop a taxonomy of econometric mod-
els  for  oil  price  forecasting;  (ii)  provide  a  critical
interpretation  of  the  different  methodologies;  and
(iii) offer a comprehensive interpretation and justifi-
cation  of  the  heterogeneous  empirical  findings  in
published oil price forecasts. The paper is structured
as  follows:  we  first  introduce  the  historical  frame-
work  which  is  necessary  to  understand  oil  price
dynamics. The  following  section  discusses  and  criti-
cally evaluates the different econometric models for
oil  price  forecasting  proposed  in  the  literature.
Finally we comment on alternative criteria for eval-
uating  and  comparing  different  forecasting  models
for oil prices.

** Forecasting the Nominal Brent Oil Price with VARs—One Model Fits All?
[[https://drive.google.com/open?id=0B0zREaCR-EN4ZmdkZXdTUENrRFk]]

We carry out an ex post assessment of popular models used to forecast oil prices and propose
a host of alternative VAR models based on traditional global macroeconomic and oil market
aggregates. While the exact specification of VAR models for nominal oil price prediction is
still open to debate, the bias and underprediction in futures and random walk forecasts are
larger across all horizons in relation to a large set of VAR specifications. The VAR forecasts
generally have the smallest average forecast errors and the highest accuracy, with most
specifications outperforming futures and random walk forecasts for horizons up to two years.
This calls for caution in reliance on futures or the random walk for forecasting, particularly
for near term predictions. Despite the overall strength of VAR models, we highlight some
performance instability, with small alterations in specifications, subsamples or lag lengths
providing widely different forecasts at times. Combining futures, random walk and VAR
models for forecasting have merit for medium term horizons.
